More error handling, UI

diff --git a/snp b/snp
--- a/snp
+++ b/snp
@@ -3,7 +3,7 @@
 snippets_dir=~/".snp"
 
 # Check for/create snippet dir
-if [ ! -d $snippets_dir ]; then
+if [[ ! -d $snippets_dir ]]; then
     echo "ERROR: $snippets_dir doesn't exist."
     echo "Create it now? [y/n]"
     read yn
@@ -15,10 +15,10 @@ if [ ! -d $snippets_dir ]; then
 fi
 
 case $1 in
-    l|list) # list
+    l|list) # List
         echo "snp snippets:\n"
         echo "$(ls -R $snippets_dir)" ;;
-    m|move) # move
+    m|move) # Move
         if [[ "$2" == "" && $3 == "" ]]; then
             echo "snp usage:\n"
             echo "snp move <name> <group>"
@@ -26,38 +26,52 @@ case $1 in
             if -d $snippets_dir/$3 ]]; then
                 mv $snippets_dir/$2 $snippets_dir/$3/$2
             else
-                echo "MOVE TO ERROR: $snippets_dir/$3 is not a group."
-                exit 1
+                echo "MOVE TO DIR ERROR: Group $snippets_dir/$3 does not exist."; exit 1
             fi
         else
-            echo "MOVE FROM ERROR: $2 is not a snippet."
-            exit 1
+            echo "MOVE FROM EXIST ERROR: Snippet $2 does not exist."; exit 1
         fi ;;
-    n|new) # new
+    n|new) # New
         if [[ "$2" == "" && "$3" == "" ]]; then
             echo "snp usage:\n"
             echo "snp new <name> \"<text>\""
             echo "snp new group <name>"
-        elif [[ "$2" == "group" && "$3" != "" ]]; then
-            mkdir $snippets_dir/$3
-        else
-            echo -n "$3" >> $snippets_dir/$2
-        fi;;
-    r|remove) # remove
+        elif [[ "$2" == "group" ]]; then # New group
+            if [[ "$3" != "" ]]; then
+                mkdir $snippets_dir/$3
+            else
+                echo "snp new group <name>"
+            fi
+        else # New snippet
+            if [[ "$3" != "" ]]; then
+                echo -n "$3" >> $snippets_dir/$2
+            else
+                echo "snp new <name> \"<text>\""
+            fi
+        fi ;;
+    r|remove) # Remove
         if [[ "$2" == "" ]]; then
             echo "snp usage:\n"
             echo "snp remove <name>"
             echo "snp remove group <name>"
-        elif [[ "$2" == "group" ]]; then
-            [[ "$3" != "" ]] && echo "REMOVE GROUP ERROR: $3 does not exist."
-            rm -rf $snippets_dir/$3
-        elif [[ "$2" != "" && -e $snippets_dir/$2 ]]; then
-            rm $snippets_dir/$2
-        else
-            echo "REMOVE ERROR: Snippet $2 does not exist."
-            exit 1
+        elif [[ "$2" == "group" ]]; then # Remove group
+            if [[ "$3" != "" ]]; then
+                if [[ -e "$3" ]]; then
+                    rm -rf $snippets_dir/$3
+                else
+                    echo "REMOVE GROUP DIR ERROR: Group $3 does not exist."; exit 1
+                fi
+            else
+                echo "snp remove group <name>"
+            fi
+        elif [[ "$2" != "" ]]; then # Remove snippet
+            if [[ -e $snippets_dir/$2 ]]; then
+                rm $snippets_dir/$2
+            else
+                echo "REMOVE SNIPPET DIR ERROR: Snippet $2 does not exist."; exit 1
+            fi
         fi ;;
-    c|copy) # copy
+    c|copy) # Copy
         if [[ "$2" == "" ]]; then
             echo "snp usage:\n"
             echo "snp copy <name> # copy snippet (to clipboard)"
@@ -65,18 +79,17 @@ case $1 in
             cat "$snippets_dir/$2" | pbcopy
             echo "Snippet text copied to clipboard."
         else
-            echo "COPY ERROR: Snippet $2 does not exist."
-            exit 1
+            echo "COPY EXIST ERROR: Snippet $2 does not exist."; exit 1
         fi ;;
     *)
         echo "snp usage:\n"
-        echo "snp new <name> \"<text>\"   # new snippet"
-        echo "snp new group <name>      # new group"
-        echo "snp list                  # list snippets"
-        echo "snp move <name> <group>   # move"
-        echo "snp remove <name>         # remove"
-        echo "snp remove group <name>   # remove group"
-        echo "snp copy <name>           # copy snippet (to clipboard)" ;;
+        echo "snp new <name> \"<text>\"   # New snippet"
+        echo "snp new group <name>      # New group"
+        echo "snp list                  # List snippets"
+        echo "snp move <name> <group>   # Move"
+        echo "snp remove <name>         # Remove snippet"
+        echo "snp remove group <name>   # Remove group"
+        echo "snp copy <name>           # Copy snippet (to clipboard)" ;;
 esac
 
 exit 0
